{
 "title": "Lab6",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Threshold DAC0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "dac0", "legendFormat": "dac0" }
   ]
  },
  {
   "title": "Threshold DAC1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "dac1", "legendFormat": "dac1" }
   ]
  },
  {
   "title": "Saltbridge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "saltbridge {}", "legendFormat": "Saltbridge" }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "humidity{}", "legendFormat": "Humidity" }
   ]
  },
  {
   "title": "Thermistor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "thermistor {}", "legendFormat": "Thermistor" }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    { "expr": "temperature {}", "legendFormat": "Temperature" }
   ]
  },
  {
   "title": "LV 3V3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "targets": [
    { "expr": "lv1 {}", "legendFormat": "LV(3.3)" }
   ]
  },
  {
   "title": "LV 3V1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 24 },
   "targets": [
    { "expr": "lv2 {}", "legendFormat": "LV (3.1)" }
   ]
  },
  {
   "title": "LV 1V8",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 24 },
   "targets": [
    { "expr": "lv3", "legendFormat": "LV (1.8)" }
   ]
  }
 ]
}